### ISSUE TITLE
[looking for help ] 

### ISSUE THREAD

**Issue by yuyu-lovegelin111333** [talamortis/cmangos-modules#2]
@talamortis  . dear sir , may you help to commit a new modules code for  cmangos-243 new version ? , If possiblely . when your's not busy some time . 

Becase currently in cmangos243, their update seem very fast and aways keep updating with core and db this 2years . the only expect things or requirement for many testers was : they need a new core modules patch ,so they can add some convenient module patch into its new mangos-tbc core .

may you help on this ? sir

**Comment by yuyu-lovegelin111333** [comment]
I think your mangos-tbc already has modules patch , but just its self need do some commit with cmangos' theire new version ?

**Comment by talamortis** [comment]
Ill take a look this weekend of pulling updates from their core and them updating the modules to support.

**Comment by yuyu-lovegelin111333** [comment]
> 

so appreciate to you and thanks so much !
